name: CI - Feature

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-unit-test:
    name: Build & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Unit Tests
        run: >
          dotnet test
          tests/CompanyName.ProjectName.UnitTests/CompanyName.ProjectName.UnitTests.csproj
          --no-build
          --configuration Release
          --logger "trx;LogFileName=unit-results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: '**/*.trx'
